### ISSUE TITLE
如何作为api来调用？

### ISSUE THREAD

**Issue by yutian81** [crazypeace/huashengdun-webssh#5]
大佬，我通过 northflank 搭建了ssh，看到你的版本支持sshlink  
如果我希望通过api来调用并直接执行命令，那么应该如何设置呢？  
比如通过 cloudflare woker 脚本来调用：  
```
// 模拟执行远程命令
async function runRemoteCommand(server, SCRIPT_URL) {
  const { SSH_USER, SSH_PASS, HOST, } = server;

  // 通过API 登录 SSH 并执行命令
  const payload = {
    hostname: HOST,
    username: SSH_USER,
    password: SSH_PASS,
    command: `bash <(curl -Ls 脚本地址})`
  };

  try {
    const response = await fetch("https://ssh.yzong.us.kg/?port=22", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    return response.ok;
  } catch (error) {
    console.error(`远程命令执行失败: ${error}`);
    return false;
  }
}
```
这里的`const response = await fetch("https://ssh.yzong.us.kg/?port=22"`api地址应该如何写？

**Comment by yutian81** [comment]
`https://ssh.yzong.us.kg/?hostname=HOST&port=22&username=SSH_USER&password=SSH_PASS&command=`   
可否这样写？是否支持以`command`参数直接执行命令？
sshlink代码我看过了，没有找到执行命令的参数

**Comment by crazypeace** [comment]
我本身并不是原作者.
sshlink的功能, 原项目就有. 我只是加了个按钮, 方便使用.-

至于你想加的功能.

在代码里搜索一下, 可以找到解析 sshlink的部分在这里
\huashengdun-webssh\webssh\handler.py
![image](https://github.com/user-attachments/assets/8ede14b6-9992-44bd-8ade-772bf8c09810)

发出指令我猜是在这里 (不是很有把握)
\huashengdun-webssh\webssh\worker.py
![image](https://github.com/user-attachments/assets/28dd85ce-1b69-456f-bec7-4fb5205a4dec)

你自己想想看怎么实现功能.
或者你试试最近比较火的 Cursor AI ?

**Comment by crazypeace** [comment]
我找了一下原项目的readme
https://github.com/huashengdun/webssh
本身就是支持传参数进去执行命令的
![image](https://github.com/user-attachments/assets/e5b98872-2f66-4784-8467-177ad7afa930)

**Comment by yutian81** [comment]
> 我找了一下原项目的readme https://github.com/huashengdun/webssh 本身就是支持传参数进去执行命令的 ![image](https://private-user-images.githubusercontent.com/665889/369602400-e5b98872-2f66-4784-8467-177ad7afa930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTEwOTMsIm5iZiI6MTcyNjkxMDc5MywicGF0aCI6Ii82NjU4ODkvMzY5NjAyNDAwLWU1Yjk4ODcyLTJmNjYtNDc4NC04NDY3LTE3N2FkN2FmYTkzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwOTI2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2Q5ZTI1MzE0N2Y1NjRhMmFlOTE3Zjk3NzhhY2JhYmJjYWYyZmRiMTRhMzkzNWI4MjdkYzBkZmY4N2E5MzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Urk7LD4HQLgmESQ3hbNz9fGeq6jGaH0duo_Nj3Y7mXA)

感谢解答，这可解决了我的大问题，我只是想通过worker来连接远程ssh并自动执行命令

**Comment by crazypeace** [comment]
期待你的项目!

**Comment by yutian81** [comment]
> 期待你的项目!

已经写好了，但还未测试是否可以正常连接。
```js
async function runRemoteCmd(vpsData, rebootScript) {
    for (const server of vpsData) {
        const { ssh, username, password } = server;
        const encodedPassword = Buffer.from(password).toString('base64');  // 使用 Buffer 进行 Base64 编码
        // 构建用于 SSH 连接的 API URL
        const sshApiUrl = `https://webssh项目域名/?hostname=${ssh}&port=22&username=${username}&password=${encodedPassword}`;  
        // 构建用于执行远程命令的 API URL
        const command = `https://webssh项目域名/?command=bash <(curl -Ls ${rebootScript})`;

        try {
            // 尝试连接 SSH
            const sshResponse = await fetch(sshApiUrl);
            if (sshResponse.ok) {
                console.log(`SSH 登录成功，执行远程命令...`);                
                // 尝试执行远程命令
                const commandResponse = await fetch(command);
                if (commandResponse.ok) {
                    console.log(`远程命令执行成功: ${commandResponse.status}`);
                } else {
                    console.log('远程命令执行失败');
                }
            } else {
                console.log('SSH 登录失败');
            }
        } catch (error) {
            console.log(`执行远程命令时出错: ${error.message}`);
        }
    }
}
```
